### PR TITLE
Adds dual.commit.enabled and offsets.storage

### PR DESCRIPTION
**Pull request by gquintana**

### CODE REVIEW

**Comment by gquintana** [comment]
@joekiller Added test case, is it enough?

**Comment by joekiller** [comment]
Thank you @gquintana!

**Comment by joekiller** [comment]
@gquintana I'm afk until next week so will push a releaseafter I return. Ideally I'll fix #55 to release your contribution but will try to package regardless.

**Comment by suyograo** [comment]
@joekiller any update on this release?

**Comment by joekiller** [comment]
should be rolling out now

**Comment by joekiller** [comment]
okay my 1_x release process was a little dated. 1.7.2 should be being pushed to rubygems soon.

**Pull request merged**
