### PR TITLE
add key/value decoder options to Group for dynamically using custom decoder for consuming kafka messages

### PR DESCRIPTION
**Pull request by talevy**
I am interested in adding config params to [logstash-input-kafka](https://github.com/logstash-plugins/logstash-input-kafka) so that people are able to apply their own decoders to either the message itself (value) or the message's key.

_example config_:
```ruby
input {
  kafka {
    topic_id => "my_avro"
    value_decoder_class => "org.personal.KafkaAvroDecoder"
  }
}
```

Unfortunately, this information will be passed in at the runtime of the plugin, so we need 
to do some reflection. This strategy leads to a few assumptions made about the constructors 
of all Decoders that are chosen. Currently, the `kafka.serializer.DefaultDecoder`'s only constructor is 
one with a `VerifiableProperties` argument. Given this, all other Decoders are assumped to have the same, even if this is unnecessary. Here is an example custom decoder for the sake of prototyping: [DotsDecoder](https://github.com/talevy/kafka-dots-serializer/blob/master/src/main/java/org/logstash/dots/DotsDecoder.java)

@joekiller, this is very much a WIP and any suggestions are welcome!

### CODE REVIEW

**Comment by talevy** [comment]
@joekiller have time to check this out?

**Comment by joekiller** [comment]
Nice, looks straightforward. Have you tested it?

**Comment by talevy** [comment]
yes, I have only tested it via https://github.com/logstash-plugins/logstash-input-kafka/pull/29

but it is kind of testing it on its own by replacing how the `DefaultDecoder` gets loaded in the default case

**Comment by talevy** [comment]
One thing I should note is that the current version of this PR will only support Decoders that 
do not utilize any `VerifiableProperties` because I hardcoded the `nil`. 

that being said. There is no way, currently, to provide your own Properties argument in the Encoder in the Producer, unless I am mistaken.

**Comment by joekiller** [comment]
This looks fine to me. The only codec that I could find that uses the properties is the default encoder.  Eventually we can just create a java properties from a map of properties for each codec but the null is fine for now.

**Comment by talevy** [comment]
thats what I figure. sweet!

**Comment by talevy** [comment]
think you'll be able to make a new release with just this commit :smile: ?

**Pull request merged**
